name: wecare
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  google_sign_in: ^6.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  change_case: ^1.1.0
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter pub run change_app_package_name:main id.eve.wecare
  change_app_package_name: ^1.1.0
  # flutter pub run flutter_app_name
  flutter_app_name: ^0.1.1
  # flutter pub run icons_launcher:create
  icons_launcher: ^2.0.4
  flutter_lints: ^2.0.0

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true

flutter_app_name:
  name: "Wecare"

flutter:
  uses-material-design: true
  assets:
    - assets/